CREATE DATABASE LibraryManagementSystem
GO
USE LibraryManagementSystem
GO

CREATE TABLE FLOOR
(
FLOORNMBER INT PRIMARY KEY,
NUMBER_OF_BLOCKS INT NOT NULL
)
GO

CREATE TABLE EMPLOYEES
(
EMP_ID INT PRIMARY KEY IDENTITY(1,1),
FNAME NVARCHAR(15),
LNAME NVARCHAR(25)NOT NULL,
ADRESS NVARCHAR(100) NOT NULL,
EMAIL NVARCHAR(30)UNIQUE NOT NULL,
SALARY DECIMAL(10,2),
DATE_OF_BIRTH DATE,
BONUS DECIMAL(10,2),
PHONE_NUMBER NVARCHAR(20),
SUPERVISOR_ID INT NULL,
FLOORNO INT NOT NULL,

CONSTRAINT FK_EMPLOYEE_SUPERVISOR 
FOREIGN KEY(SUPERVISOR_ID)
REFERENCES EMPLOYEES(EMP_ID),

CONSTRAINT FK_EMPLOYEE_FLOOR
FOREIGN KEY (FLOORNO)
REFERENCES FLOOR(FLOORNMBER)
)
GO

CREATE TABLE USERLIBARAY
(
SSN VARCHAR(15) PRIMARY KEY,
NAME NVARCHAR(30) NOT NULL,
EMAIL VARCHAR(50)UNIQUE,
EMP_ID INT NOT NULL ,

CONSTRAINT FK_EMPLOYEE_ID
FOREIGN KEY(EMP_ID)
REFERENCES EMPLOYEES(EMP_ID)
)
GO

CREATE TABLE SHELF
(
CODE VARCHAR(15) PRIMARY KEY,
FLOORNO INT NOT NULL ,
CONSTRAINT FK_FLOORNUMBER
FOREIGN KEY(FLOORNO)
REFERENCES FLOOR(FLOORNMBER)
)

GO
CREATE TABLE BOOK
(
BOOK_ID INT PRIMARY KEY IDENTITY(1,1),
TITLE NVARCHAR(20) NOT  NULL,
PUBLISHER_ID INT NOT NULL,
CAT_ID INT NOT NULL,
SHELF_CODE VARCHAR(15) NOT NULL,
CONSTRAINT FK_BOOK_SHELF
FOREIGN KEY (SHELF_CODE)
REFERENCES SHELF(CODE) 
)

GO
CREATE TABLE PUBLISHER
(
ID INT PRIMARY KEY,
NAME NVARCHAR(30) NOT NULL
)
GO
CREATE TABLE AUTHOR
(
ID INT PRIMARY KEY,
NAME NVARCHAR(30) NOT NULL
)
GO
CREATE TABLE BOOK_AUTHOR
(
    AUTHOR_ID INT,
    BOOK_ID INT,

    CONSTRAINT PK_BOOK_AUTHOR
        PRIMARY KEY (AUTHOR_ID, BOOK_ID),

    CONSTRAINT FK_BOOK_AUTHOR_AUTHOR
        FOREIGN KEY (AUTHOR_ID)
        REFERENCES AUTHOR(ID),

    CONSTRAINT FK_BOOK_AUTHOR_BOOK
        FOREIGN KEY (BOOK_ID)
        REFERENCES BOOK(BOOK_ID)
);
GO
CREATE TABLE CATEGORY
(
CAT_ID INT PRIMARY KEY,
CAT_NAME NVARCHAR(50) NOT NULL
)
GO
CREATE TABLE BORROW
(

BORROW_ID INT PRIMARY KEY IDENTITY(1,1),
BOOK_ID INT NOT  NULL FOREIGN KEY 
REFERENCES BOOK(BOOK_ID),

USER_SSN VARCHAR(15) NOT NULL FOREIGN KEY 
REFERENCES USERLIBARAY(SSN),


EMP_ID INT NOT NULL FOREIGN KEY 
REFERENCES EMPLOYEES(EMP_ID),

DATE_BORROWED DATETIME NOT NULL,
DUE_DATE DATETIME NOT NULL,
AMOUNT_OF_MONEY DECIMAL(10,2) NOT NULL
)
GO
ALTER TABLE FLOOR 
ADD MANAGER_ID INT NOT NULL UNIQUE ,
HIRING_DATE DATE NOT NULL
GO
ALTER TABLE FLOOR
ADD CONSTRAINT FK_Floor_Manager
FOREIGN KEY(MANAGER_ID)
REFERENCES EMPLOYEES(EMP_ID)
GO

   CREATE TABLE USER_PHONE
   (
   USER_SSN VARCHAR(15),
   PHONE  VARCHAR(20),
   PRIMARY KEY(USER_SSN,PHONE),
   CONSTRAINT FK_USER_SSN
   FOREIGN KEY(USER_SSN)
   REFERENCES USERLIBARAY(SSN)
   )

   GO
ALTER TABLE BOOK
ADD CONSTRAINT FK_BOOK_PUBLISHER
FOREIGN KEY(PUBLISHER_ID)
REFERENCES PUBLISHER(ID)
GO
ALTER TABLE BOOK
ADD CONSTRAINT FK_BOOK_CATEGORY
FOREIGN KEY(CAT_ID)
REFERENCES CATEGORY(CAT_ID)
GO