---part_2---
USE LibraryManagementSystem
GO

--1--
SELECT CONCAT(FNAME,' ',LNAME) AS "FULL NAME"
FROM EMPLOYEES
WHERE LEN(FNAME)>3;

---2---
SELECT COUNT(*) AS "NO OF PROGRAMMING BOOKS"
FROM Book
WHERE Category = 'Programming';

--3--
SELECT COUNT(*) AS 'NO_OF_BOOKS'
FROM BOOK JOIN PUBLISHER
ON BOOK.PUBLISHER_ID = PUBLISHER.ID
WHERE PUBLISHER.NAME = 'HarperCollins';

--4--
SELECT U.SSN , U.NAME, B.DATE_BORROWED,B.DUE_DATE
FROM USERLIBARAY U JOIN BORROW B
ON B.USER_SSN = U.SSN
WHERE B.DUE_DATE < '2022-07-01'

--5--
SELECT CONCAT(B.TITLE,' IS WRITTEN BY ',A.NAME,' .')
FROM BOOK B JOIN BOOK_AUTHOR BA
ON B.BOOK_ID = BA.BOOK_ID 
JOIN AUTHOR A
ON A.ID = BA.AUTHOR_ID;

--6--
SELECT NAME
FROM USERLIBARAY
WHERE NAME LIKE '%A%';

--7--
SELECT TOP(1) B.USER_SSN
FROM  BORROW B
GROUP BY B.USER_SSN
ORDER BY COUNT(*) DESC;

--8--
SELECT SUM(AMOUNT_OF_MONEY) AS "TOTAL AMOUNT OF MONEY"
FROM BORROW
GROUP BY USER_SSN

--9--
SELECT TOP(1) C.CAT_NAME
FROM BOOK B JOIN BORROW BW
ON B.BOOK_ID = BW.BOOK_ID
JOIN CATEGORY C
ON C.CAT_ID = B.CAT_ID
ORDER BY AMOUNT_OF_MONEY 

--10--
SELECT COALESCE(EMAIL,ADRESS,CONVERT(VARCHAR,DATE_OF_BIRTH,25)) AS [Employee Info]
FROM EMPLOYEES

--11--
SELECT C.CAT_NAME, COUNT(*)AS [Count Of Books]
FROM BOOK B JOIN CATEGORY C 
ON B.CAT_ID = C.CAT_ID
GROUP BY C.CAT_NAME

--12--
SELECT B.BOOK_ID
FROM BOOK B JOIN SHELF S
ON B.SHELF_CODE = S.CODE
JOIN FLOOR F
ON F.FLOORNMBER = S.FLOORNO
WHERE F.FLOORNMBER <> 1 OR S.CODE <> 'A1'

--13--
SELECT F.FLOORNMBER,F.NUMBER_OF_BLOCKS, COUNT(E.FLOORNO) AS [ NUMBER OF EMPLOYEES]
FROM EMPLOYEES E RIGHT JOIN FLOOR F
ON E.FLOORNO = F.FLOORNMBER
GROUP BY F.FLOORNMBER,F.NUMBER_OF_BLOCKS;

--14--
SELECT B.TITLE ,U.NAME
FROM BOOK B JOIN BORROW BW
ON B.BOOK_ID = BW.BOOK_ID
JOIN USERLIBARAY U
ON U.SSN = BW.USER_SSN
WHERE BW.DATE_BORROWED BETWEEN '20220301' AND '20221001'

--15--
SELECT CONCAT(E.FNAME,' ',E.LNAME) AS [EMPLOYEE NAME], CONCAT(M.FNAME,' ',M.LNAME) AS [SUPERVISOR NAME]
FROM EMPLOYEES E LEFT JOIN EMPLOYEES M
ON E.SUPERVISOR_ID = M.EMP_ID

--16--
SELECT CONCAT(E.FNAME,' ',E.LNAME) AS [EMPLOYEE NAME], COALESCE(E.SALARY,E.BONUS)
FROM EMPLOYEES E

--17--
SELECT MAX(SALARY) AS "MAX SALARY" , MIN(SALARY) AS "MIN SALARY"
FROM EMPLOYEES

--18--
GO
CREATE FUNCTION TYPEOFNUM(@NUM INT)
RETURNS VARCHAR(10)
AS
BEGIN
IF (@NUM % 2 = 0)
RETURN  'EVEN'

RETURN  'ODD'
END
GO
SELECT DBO.TYPEOFNUM(8)

--19--
GO
CREATE FUNCTION GetBooksByCategory(@CATEGORYName nvarchar(20))
RETURNS TABLE
AS
RETURN
(
SELECT B.TITLE 
FROM BOOK B JOIN CATEGORY C
ON B.CAT_ID = C.CAT_ID
WHERE C.CAT_NAME = @CATEGORYName
)
GO
SELECT * FROM DBO.GetBooksByCategory('FICTION');

--20--
GO
CREATE FUNCTION USERINFO(@PHONE VARCHAR(20))
RETURNS TABLE
AS
RETURN
(
SELECT BK.TITLE,UL.NAME,B.AMOUNT_OF_MONEY,B.DUE_DATE
FROM USER_PHONE UP JOIN USERLIBARAY UL
ON UP.USER_SSN = UL.SSN
JOIN BORROW B
ON UP.USER_SSN = B.USER_SSN
JOIN BOOK BK
ON BK.BOOK_ID = B.BOOK_ID
WHERE UP.PHONE = @PHONE
)
GO
SELECT * FROM DBO.USERINFO('01044445555')

---21---
GO

CREATE FUNCTION CKECKDUPLICATE
(
    @USERNAME NVARCHAR(30)
)
RETURNS NVARCHAR(100)
AS
BEGIN
    DECLARE @COUNT INT
    DECLARE @MESSAGE NVARCHAR(100)

    SELECT @COUNT = COUNT(*)
    FROM USERLIBARAY
    WHERE NAME = @USERNAME

    IF (@COUNT = 0)
    BEGIN
        SET @MESSAGE = @USERNAME + ' IS NOT FOUND'
    END
    ELSE IF (@COUNT = 1)
    BEGIN
        SET @MESSAGE = @USERNAME + ' IS NOT DUPLICATED'
    END
    ELSE
    BEGIN
        SET @MESSAGE = @USERNAME + ' IS REPEATED '
                     + CAST(@COUNT AS VARCHAR(10))
                     + ' TIMES'
    END

    RETURN @MESSAGE
END
GO

SELECT dbo.CKECKDUPLICATE('Yasmin Adel')
--22--
GO
CREATE FUNCTION DATEFORMAT(@INPUTDATE DATE,@FORMAT VARCHAR(30))
RETURNS NVARCHAR(50)
AS
BEGIN
DECLARE @RESULT NVARCHAR(50)
SET @RESULT = FORMAT(@INPUTDATE,@FORMAT)
RETURN @RESULT
END
GO
SELECT DBO.DATEFORMAT('2026-08-30', 'MMMM dddd, yy' )

--23--
GO
CREATE PROCEDURE NUMBEROFBOOKS
AS
BEGIN
SELECT C.CAT_NAME,COUNT(*) AS "NUMBER OF BOOKS"
FROM CATEGORY C JOIN BOOK B
ON B.CAT_ID = C.CAT_ID
GROUP BY C.CAT_NAME
END
GO
EXEC NUMBEROFBOOKS 

--24--
GO
CREATE PROCEDURE UPDATEMANAGER @OLDMANG INT ,@NEWMANG INT , @FLOORNO INT
AS
BEGIN 
UPDATE FLOOR
SET MANAGER_ID = @NEWMANG
WHERE FLOORNMBER = @FLOORNO AND
MANAGER_ID = @OLDMANG
END
GO
EXEC UPDATEMANAGER 4,3,2

--25--
GO
CREATE VIEW AlexAndCairoEmp
AS
SELECT *
FROM EMPLOYEES
WHERE ADRESS IN ('CAIRO','Alex')
GO
SELECT * FROM AlexAndCairoEmp

--26--
GO
CREATE VIEW V2
AS
SELECT S.CODE,COUNT(*) AS "NUMBER OF BOOKS"
FROM BOOK B JOIN SHELF S
ON B.SHELF_CODE = S.CODE
GROUP BY S.CODE
GO
SELECT * FROM V2
--27--
GO
CREATE VIEW V3
AS
SELECT CODE,[NUMBER OF BOOKS]
FROM V2
WHERE [NUMBER OF BOOKS] = (SELECT MAX([NUMBER OF BOOKS]) FROM V2)
GO
SELECT * FROM V3
--28--
GO
CREATE TABLE ReturnedBooks
(
USER_SSN VARCHAR(30),
BOOK_ID INT,
DUE_DATE DATETIME,
RETURN_DATE DATETIME,
FEES DECIMAL(10,2)
)
GO
CREATE TRIGGER TR_ReturnedBooks
ON ReturnedBooks
INSTEAD OF INSERT
AS
BEGIN
SET NOCOUNT ON
INSERT INTO ReturnedBooks(USER_SSN,BOOK_ID,DUE_DATE,RETURN_DATE,FEES)
SELECT  I.USER_SSN,I.BOOK_ID,I.DUE_DATE,I.RETURN_DATE,
CASE
WHEN I.DUE_DATE = I.RETURN_DATE
THEN  0
ELSE
 B.AMOUNT_OF_MONEY * 0.20
 END

FROM inserted I JOIN BORROW B
ON I.USER_SSN = B.USER_SSN AND I.BOOK_ID = B.BOOK_ID
END
GO

INSERT INTO FLOOR (FLOORNMBER, NUMBER_OF_BLOCKS, MANAGER_ID, HIRING_DATE)
VALUES (6, 2, 20, GETDATE());

DECLARE @OldFloor INT;
SELECT @OldFloor = FLOORNMBER FROM FLOOR WHERE MANAGER_ID = 5;

UPDATE FLOOR
SET MANAGER_ID = 12
WHERE FLOORNMBER = @OldFloor;


UPDATE FLOOR
SET MANAGER_ID = 5
WHERE FLOORNMBER = 6;

UPDATE EMPLOYEES SET FLOORNO = 6    
WHERE EMP_ID = 5;  

UPDATE EMPLOYEES SET FLOORNO = @OldFloor
WHERE EMP_ID = 12;
--30--
GO
CREATE VIEW v_2006_check
AS
SELECT E.EMP_ID,F.FLOORNMBER,F.NUMBER_OF_BLOCKS,F.HIRING_DATE
FROM EMPLOYEES E JOIN FLOOR F
ON E.FLOORNO = F.FLOORNMBER
WHERE F.HIRING_DATE BETWEEN '2022-03-01' AND '2022-05-31'
WITH CHECK OPTION
GO
SELECT * FROM v_2006_check

--31--
GO
CREATE TRIGGER TR_PREVENT_EMPLOYEES_ACTIONS
ON EMPLOYEES
INSTEAD OF INSERT, UPDATE, DELETE
AS
BEGIN
    RAISERROR('You cannot take any action on EMPLOYEES table.', 16, 1);
END

--32--

/* =========================================================
   32. Testing Referential Integrity
   ========================================================= */


/* A. Add a new User Phone Number with User_SSN = 50
   Expected:
   INSERT will fail if SSN = 50 does not exist in USERS.
*/
INSERT INTO USER_PHONE
VALUES (50, '01012345678');
GO


/* B. Modify Employee ID 20 to 21
   Expected:
   UPDATE will fail if Employee 20 is referenced
   by a Foreign Key in another table.
*/
UPDATE EMPLOYEES
SET EMP_ID = 21
WHERE EMP_ID = 20;
GO


/* C. Delete Employee with ID = 1
   Expected:
   DELETE will fail if Employee 1 is referenced
   by a Foreign Key in another table.
*/
DELETE FROM EMPLOYEES
WHERE EMP_ID = 1;
GO


/* D. Delete Employee with ID = 12
   Expected:
   DELETE will succeed if Employee 12 is not referenced
   by any Foreign Key.
   Otherwise, it will fail.
*/
DELETE FROM EMPLOYEES
WHERE EMP_ID = 12;
GO


/* E. Create a Clustered Index on Salary
   NOTE:
   SQL Server allows only ONE clustered index per table.
   If EMP_ID already has a clustered index, this statement
   will fail until the existing clustered index is changed/dropped.
*/
CREATE CLUSTERED INDEX IX_EMPLOYEES_SALARY
ON EMPLOYEES(SALARY);
GO


--33--
CREATE LOGIN ABDULLAHLOGIN
WITH PASSWORD = '1234@ABDULLAH'

GO
USE LibraryManagementSystem
GO

CREATE USER ABDULLAH
FOR LOGIN ABDULLAHLOGIN

GRANT SELECT,INSERT
ON EMPLOYEES
TO ABDULLAH

GRANT SELECT,INSERT
ON FLOOR
TO ABDULLAH

DENY UPDATE ,DELETE
ON EMPLOYEES
TO ABDULLAH

DENY UPDATE,DELETE
ON FLOOR
TO ABDULLAH